export type createPaymentInitialValues = {
  businessUC: string;
  id: number;
  publishableKey: string;
  secretKey: string;
  paymentMethod: string;
  accountName: string;
  countryName: string;
  // accessToken: string;
  // clientId: string;
  // webhook: string;
  // clientSecret: string;
  isActive: boolean;
  // bankName: string;
  // accountHolder: string;
  // ibanNumber: string;
  // accountNumber: string;
  // sortCode: string;
  // bic: string;
};
